notifications:
  email: false

matrix:
  fast_finish: true

sudo: required

language: python

services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d

script:
  - sleep 5
  - curl -s http://127.0.0.1/ | grep -q Invenio
